language: cpp

matrix:
  include:

    - os: linux
      addons:
        apt:
          packages:
            - python-dev
            - ninja-build

script:
  
  - mkdir build
  - cd build 
  
  - cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build .
  - cmake --build . --target test
